### ISSUE TITLE
Action fails due to "missing file"

### ISSUE THREAD

**Issue by makspll** [houseabsolute/actions-rust-cross#15]
Action log can be seen here: https://github.com/makspll/bevy_mod_scripting/actions/runs/8552685284/job/23434311319?pr=67

the relevant error is:

```
 error: failed to load manifest for workspace member `/project/crates/bevy_script_api`
Caused by:
  failed to load manifest for dependency `bevy_mod_scripting_lua_derive`
Caused by:
  failed to load manifest for dependency `bevy_mod_scripting`
Caused by:
  failed to read `/bevy_mod_scripting/Cargo.toml`
Caused by:
  No such file or directory (os error 2)
Error: Process completed with exit code 101.
```

And the workflow looks like this:
```yaml
jobs:
  check:
    name: Check
    runs-on: ${{ matrix.run_args.os }}
    strategy:
      matrix:
       run_args: [ 
        {os: windows-latest,      lua: lua54,     cross: null}, 
        {os: macOS-latest,        lua: lua54,     cross: null},
        {os: ubuntu-latest,       lua: lua54,     cross: aarch64-unknown-linux-gnu},
        {os: ubuntu-latest,       lua: lua51,     cross: null}, 
        {os: ubuntu-latest,       lua: lua52,     cross: null}, 
        {os: ubuntu-latest,       lua: lua53,     cross: null}, 
        {os: ubuntu-latest,       lua: lua54,     cross: null}, 
        {os: ubuntu-latest,       lua: luajit,    cross: null}, 
        {os: ubuntu-latest,       lua: luajit52,  cross: null}
      ]
    steps:
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
      # for x86 builds
      - if: matrix.run_args.cross == null
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --features=${{ matrix.run_args.lua }},rhai,teal,lua_script_api,rhai_script_api,rune
      # for non x86 cross-compiled builds
      - if: matrix.run_args.cross != null
        name: Clear space
        run: sudo rm -rf /usr/share/dotnet; sudo rm -rf /opt/ghc; sudo rm -rf "/usr/local/share/boost"; sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - if: matrix.run_args.cross != null
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: check
          target: ${{ matrix.run_args.cross }}
          args: --workspace --features=${{ matrix.run_args.lua }},rhai,teal,lua_script_api,rhai_script_api,rune --profile=ephemeral-build

```
