### ISSUE TITLE
Binaries not being built?

### ISSUE THREAD

**Issue by lokimckay** [houseabsolute/actions-rust-cross#16]
Build step using `houseabsolute/actions-rust-cross@v0` completes successfully, but only empty `build` `deps` `examples` and `incremental` folders are generated in the working directory

Did the binaries escape somewhere else?

Example run: https://github.com/deltasiege/godot-rapier-3d/actions/runs/9044423295/job/24853052477

EDIT: Running the same command locally as reported in the example run yields the binaries as expected

```
cross +stable build --locked --release --target i686-unknown-linux-gnu
...
ls target\i686-unknown-linux-gnu\release\

drwxr-xr-x 1 loki 197121       0 May 12 01:22 ./
drwxr-xr-x 1 loki 197121       0 May 12 01:20 ../
-rw-r--r-- 1 loki 197121       0 May 12 01:20 .cargo-lock
drwxr-xr-x 1 loki 197121       0 May 12 01:20 .fingerprint/
drwxr-xr-x 1 loki 197121       0 May 12 01:20 build/
drwxr-xr-x 1 loki 197121       0 May 12 01:22 deps/
drwxr-xr-x 1 loki 197121       0 May 12 01:20 examples/
drwxr-xr-x 1 loki 197121       0 May 12 01:20 incremental/
-rw-r--r-- 1 loki 197121    1155 May 12 01:22 libgodot_rapier_3d.d
-rw-r--r-- 2 loki 197121 9645240 May 12 01:22 libgodot_rapier_3d.so
```

Workflow:
```yml
# https://github.com/marketplace/actions/build-rust-projects-with-cross
# https://github.com/houseabsolute/precious/blob/master/.github/workflows/ci.yml
name: Release binaries

on:
  workflow_dispatch:
  push:
    paths:
      - "addons/godot-rapier-3d/rust/**"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # Regex for a version number such as 0.2.1

defaults:
  run:
    working-directory: addons/godot-rapier-3d/rust

jobs:
  release:
    name: Release - ${{ matrix.release_for }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - release_for: linux-x32-gnu
            os: ubuntu-latest
            target: i686-unknown-linux-gnu
            bin: godot_rapier_3d.linux.release.x86_32.so
            archive: linux-gnu-x86_32.tar.gz

          # - release_for: macos-x64-darwin
          #   os: macos-latest
          #   target: x86_64-apple-darwin
          #   bin: godot_rapier_3d.macos.release.framework
          #   archive: macos-darwin-x86_64.tar.gz

          # - release_for: windows-x64-gnu
          #   os: windows-latest
          #   target: x86_64-pc-windows-gnu
          #   bin: godot_rapier_3d.windows.release.x86_64.dll
          #   archive: windows-gnu-x86_64.zip

    steps:
      - uses: actions/checkout@v4
      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Determine version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true
          working-directory: "addons/godot-rapier-3d/rust"
      - name: List target dir
        shell: bash
        run: |
          ls -la ./target/release
          echo ---
          ls -la ./
          echo ---
          ls -la ../
          echo ---
          ls -la ../../
          echo ---
          ls -la ../../../
          echo ---
          ls -la ../../../../
      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ../../../godot_rapier_3d-${{ env.VERSION }}-${{ matrix.archive }} ${{ matrix.bin }}
          else
            tar czvf ../../../godot_rapier_3d-${{ env.VERSION }}-${{ matrix.archive }} ${{ matrix.bin }}
          fi
          cd -
      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godot_rapier_3d-${{ matrix.os_name }}
          path: "godot_rapier_3d-*"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: "godot_rapier_3d-*"
          body_path: CHANGES.md
```
