### ISSUE TITLE
UBI bootstrap script unable to setup cross-rs

### ISSUE THREAD

**Issue by serle** [houseabsolute/actions-rust-cross#18]
I'm trying to build for apple silicone, with the following action config

```
build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: aarch64-apple-darwin
          toolchain: nightly
          cross-version: "v0.2.5"
          args: "--locked --release"
          strip: true
```

I'm getting output 

```
...
bootstrap-ubi.sh: ubi has been installed to ..
| bootstrap-ubi.sh: It looks like . is not in your PATH. You may want to add it to use ubi.
| 
| + ./ubi --project cross-rs/cross --matching musl --in . --tag v0.2.5
| [ubi][ERROR] HTTP status client error (401 Unauthorized) for url (https://api.github.com/repos/cross-rs/cross/releases/tags/v0.2.5)
```

**Comment by autarch** [comment]
That's odd. Can you point me to the project with this config or is it private?

**Comment by k-o-n-t-o-r** [comment]
We encountered the same issue when using this action in a workflow on a GitHub Enterprise instance. The problem arises because the action attempts to authenticate with `github.com` using the token from `$GITHUB_TOKEN`, which isn't valid because it's only applicable to the instance that issued it.

To resolve this, we generated a PAT for `github.com` and used it to override the respective environment variable in the workflow. 

```yaml
  - name: Build binary
    uses: houseabsolute/actions-rust-cross@v0
    with:
      GITHUB_TOKEN: ${{secrets.GITHUB_DOT_COM_TOKEN}}
```
