### ISSUE TITLE
rustup and interfaction with Swatinem/rust-cache

### ISSUE THREAD

**Issue by jennydaman** [houseabsolute/actions-rust-cross#23]
Hi, I am wondering how to use this properly with `Swatinem/rust-cache`. The README says

https://github.com/houseabsolute/actions-rust-cross/blob/ad283b2fc65ad1f3a04fb8bf8b2b829aad4a9318/README.md?plain=1#L89-L93

However, `Swatinem/rust-cache` README says

> selecting a toolchain either by action or manual `rustup` calls should happen
> before the plugin, as the cache uses the current rustc version as its cache key

https://github.com/Swatinem/rust-cache/blob/9bdad043e88c75890e36ad3bbc8d27f0090dd609/README.md?plain=1#L11-L12

I see that `houseabsolute/actions-rust-cross` calls `dtolnay/rust-toolchain@master`, which is a wrapper around `rustup`

https://github.com/houseabsolute/actions-rust-cross/blob/d788e00f158ff5102cc3d4707b24be96c264a5bc/action.yml#L43-L46

So if you have something like

```yaml
- uses: Swatinem/rust-cache@v2
- uses: houseabsolute/actions-rust-cross@v0
  with:
    taget: x86_64-unknown-linux-musl
```

What ends up happening is `rustup` gets executed before `Swatinem/rust-cache`
