### ISSUE TITLE
unable to get `aarch-unknown-linux-gnu` target, w os: `ubuntu-latest` + `ubuntu-latest-arm` (custom image)

### ISSUE THREAD

**Issue by skilbjo** [houseabsolute/actions-rust-cross#25]
hi, i'm trying to build a dynamic lib for a linux-arm target (`aarch-unknown-linux-gnu`) and having some trouble.

because the default github actions runner for `ubuntu-latest` is x86, i created a custom github-hosted image called `ubuntu-latest-arm` which is just ubuntu@24 but on arm architecture.

here is the github-actions config:

```
  build-rust-cross:
    timeout-minutes: 10
    name: build rust cross - ${{ matrix.platform.release_for }}

    strategy:
      matrix:
        platform:
          ## arm runner
          - release_for: linux-arm
            os: ubuntu-latest-arm
            target: aarch64-unknown-linux-gnu
            name: lib.so

          ## x86 runner, but uses cross to get arm target
          - release_for: linux-arm
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: lib.so

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
```

and here's the log output for `ubuntu-latest-arm`
```
downloading https://github.com/houseabsolute/ubi/releases/latest/download/ubi-Linux-aarch64-musl.tar.gz
ubi-Linux-aarch64-musl.tar.gz

bootstrap-ubi.sh: ubi has been installed to `.`.
bootstrap-ubi.sh: It looks like `.` is not in your PATH. You may want to add it to use ubi.
+ ./ubi --project cross-rs/cross --matching musl --in . --tag v0.2.5

[ubi][ERROR] could not find a release for this OS and architecture (aarch64-unknown-linux-musl) from cross-x86_64-apple-darwin.tar.gz, cross-x86_64-pc-windows-msvc.tar.gz, cross-x86_64-unknown-linux-gnu.tar.gz, cross-x86_64-unknown-linux-musl.tar.gz
```

and the `ubuntu-latest` / `target: aarch64-unknown-linux-gnu`:

```
  /target/aarch64-unknown-linux-gnu/release/build/rboring-sys-f9ae40323be14a57/out/boringssl/src/include/openssl/base.h:59:10: fatal error: 'stddef.h' file not found
  thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/clang-sys-1.8.1/src/lib.rs:1859:1:
  A `libclang` function was called that is not supported by the loaded `libclang` instance.
      called function = `clang_getTranslationUnitTargetInfo`
      loaded `libclang` instance = 3.8.x
  The minimum `libclang` requirement for this particular function can be found here:
  https://docs.rs/clang-sys/latest/clang_sys/clang_getTranslationUnitTargetInfo/index.html
  Instructions for installing `libclang` can be found here:
  https://rust-lang.github.io/rust-bindgen/requirements.html
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
