### ISSUE TITLE
Add: bench command

### ISSUE THREAD

**Issue by RaulTrombin** [houseabsolute/actions-rust-cross#31]
Hello, can we add bench command?

I tested it and use to compile armv7/aarch on CI and then just run binaries on self-hosted.

https://github.com/RaulTrombin/actions-rust-cross/tree/add_bench

```
 - name: Cross-compile benchmark
        uses: RaulTrombin/actions-rust-cross@add_bench
        with:
          command: bench
          target: ${{ matrix.TARGET }}
          args: "--no-run"
```
