### ISSUE TITLE
Support sccache

### ISSUE THREAD

**Issue by orf** [houseabsolute/actions-rust-cross#33]
Hey! Awesome action <3

It would be amazing to support sccache with this action. It's possible right now, but fiddly: I've hacked it in with:

```yaml
      # From https://github.com/mozilla/sccache/blob/main/docs/GHA.md
      - name: Configure sccache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        env:
          CROSS_CONFIG: "cross/Cross.sccache.toml"
          RUSTC_WRAPPER: "sccache"
        with:
          target: ${{ matrix.platform.target }}
```

With 

```toml
[build.dockerfile]
file = "cross/cross.sccache.Dockerfile"

[build.env]
passthrough = [
    "SCCACHE_GHA_ENABLED",
    "ACTIONS_CACHE_URL",
    "ACTIONS_RUNTIME_TOKEN",
    "RUSTC_WRAPPER=sccache"
]
```

And the dockerfile:

```dockerfile
ARG CROSS_BASE_IMAGE
FROM $CROSS_BASE_IMAGE
ARG DEBIAN_FRONTEND=noninteractive

COPY cross/sccache.sh /sccache.sh
RUN /sccache.sh x86_64-unknown-linux-musl

ENV RUSTC_WRAPPER="/usr/bin/sccache"
```

with the script [from the cross wiki](https://github.com/cross-rs/cross/wiki/Recipes#sccache).
