### ISSUE TITLE
Support caching cross-rs download

### ISSUE THREAD

**Issue by timon-schelling** [houseabsolute/actions-rust-cross#4]
Thanks for creating this action, exactly what I needed.

I would like to propose the implementation of the GitHub actions caching mechanism for Rust cross download. This would significantly improve build times by removing the need for redundant downloads across runs.

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

I'll try to come up with a solution myself, but I'm probably not knowledgeable enough in GitHub action development.

**Comment by autarch** [comment]
Hmm, for some weird reason I didn't get an email when you made this issue. Glad I found it!

Yes, this sounds like a great idea. I'll take a look. It shouldn't be too hard.

**Comment by timon-schelling** [comment]
```
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.3.3
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('.github/workflows/build.yaml') }}
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          command: "build"
```

I tried this but downloading and unpacking from Cache is actualy slower than pulling the docker image. I Hope you find a better way.

Btw, supporting caching for builds inside cross containers could also help build times.
