### ISSUE TITLE
Support installing a specific version of nightly

### ISSUE THREAD

**Issue by axos88** [houseabsolute/actions-rust-cross#42]
Similar to

```
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2025-01-12
```
